export enum Limits {
  ENERGY_LIMITED,
  TIME_LIMITED,
  MONEY_LIMITED,
  SCHEDULE_1_ENABLED,
  SCHEDULE_2_ENABLED,
  SCHEDULE_1_ENERGY,
  SCHEDULE_1_CURRENT,
  SCHEDULE_2_ENERGY,
  SCHEDULE_2_CURREN,
  EVSE_ENABLED,
  LIMITS_SUSPENDED,
  DELAYED_LIMIT,
  ERRORS_SUSPENDED,
  SCHEDS_SUSPENDED,
}

export enum SecurityCtrl {
  RelayCheck = 1,
  LeakCheck = 2,
}
